### ISSUE TITLE
FILESEXTRAPATHS needs ":" to be compatible with further bbappends

### ISSUE THREAD

**Issue by JM-Anderson** [adps/meta-adlnx#1]
For the admvpx39z2-thud branch, the line in recipes-kernel/linux/linux-xlnx_2018.3.bbappend
```
FILESEXTRAPATHS_append := "${THISDIR}/files"
```
needs to be changed to 
```
FILESEXTRAPATHS_append := "${THISDIR}/files:"
```
to allow other layers to append to `FILESEXTRAPATHS` with their directories. This caused an error for me when trying to include my own kernel configuration fragment in a custom layer.

**Comment by emmah91** [comment]
Fixed.
